language: php

php:
  - 5.6
  - 7.0 

env:
  global:
    - DEFAULT=1

matrix:
  include:
  - php: 5.6 
    env: PHPCS=1 DEFAULT=0
  - php: 7.0
    env: PHPCS=1 DEFAULT=0

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev

before_script:
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"
  - phpenv rehash

script:
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src; fi"

notifications:
  email:
    on_success: never
    on_failure: change
